name: Mobile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mobile-ci:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install root dependencies
      run: npm install
      
    - name: Install mobile dependencies
      run: |
        cd mobile
        npm install
        
    - name: Run mobile tests
      run: |
        cd mobile
        npm test
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mobile-test-results
        path: mobile/coverage 